// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: configs.sql

package sqlc

import (
	"context"
)

const deleteConfig = `-- name: DeleteConfig :execrows
DELETE FROM configs WHERE key = ?
`

func (q *Queries) DeleteConfig(ctx context.Context, key string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteConfig, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getConfig = `-- name: GetConfig :one
SELECT id, key, value, updated_at FROM configs WHERE key = ?
`

func (q *Queries) GetConfig(ctx context.Context, key string) (Config, error) {
	row := q.db.QueryRowContext(ctx, getConfig, key)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}

const setConfig = `-- name: SetConfig :exec
INSERT INTO configs (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetConfigParams struct {
	Key   string
	Value string
}

func (q *Queries) SetConfig(ctx context.Context, arg SetConfigParams) error {
	_, err := q.db.ExecContext(ctx, setConfig, arg.Key, arg.Value)
	return err
}
