// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlists.sql

package sqlc

import (
	"context"
	"time"
)

const createPlaylist = `-- name: CreatePlaylist :execlastid
INSERT INTO playlists (type, name, description, cover_path, cover_url, labels, position)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreatePlaylistParams struct {
	Type        string
	Name        string
	Description string
	CoverPath   string
	CoverUrl    string
	Labels      string
	Position    int64
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createPlaylist,
		arg.Type,
		arg.Name,
		arg.Description,
		arg.CoverPath,
		arg.CoverUrl,
		arg.Labels,
		arg.Position,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deletePlaylist = `-- name: DeletePlaylist :execrows
DELETE FROM playlists WHERE id = ?
`

func (q *Queries) DeletePlaylist(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePlaylist, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findPlaylistByName = `-- name: FindPlaylistByName :one
SELECT id FROM playlists WHERE name = ? LIMIT 1
`

func (q *Queries) FindPlaylistByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, findPlaylistByName, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findPlaylistByNameExcludeID = `-- name: FindPlaylistByNameExcludeID :one
SELECT id FROM playlists WHERE name = ? AND id != ? LIMIT 1
`

type FindPlaylistByNameExcludeIDParams struct {
	Name string
	ID   int64
}

func (q *Queries) FindPlaylistByNameExcludeID(ctx context.Context, arg FindPlaylistByNameExcludeIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, findPlaylistByNameExcludeID, arg.Name, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getMaxPlaylistPosition = `-- name: GetMaxPlaylistPosition :one
SELECT CAST(COALESCE(MAX(position), 0) AS INTEGER) FROM playlists
`

func (q *Queries) GetMaxPlaylistPosition(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMaxPlaylistPosition)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getPlaylistByID = `-- name: GetPlaylistByID :one
SELECT p.id, p.type, p.name, p.description, p.cover_path, p.cover_url, p.labels,
    p.position, p.created_at, p.updated_at,
    COALESCE(cnt.song_count, 0) as song_count
FROM playlists p
LEFT JOIN (SELECT playlist_id, COUNT(*) as song_count FROM playlist_songs WHERE playlist_id = ? GROUP BY playlist_id) cnt
ON p.id = cnt.playlist_id
WHERE p.id = ?
`

type GetPlaylistByIDParams struct {
	PlaylistID int64
	ID         int64
}

type GetPlaylistByIDRow struct {
	ID          int64
	Type        string
	Name        string
	Description string
	CoverPath   string
	CoverUrl    string
	Labels      string
	Position    int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	SongCount   int64
}

func (q *Queries) GetPlaylistByID(ctx context.Context, arg GetPlaylistByIDParams) (GetPlaylistByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPlaylistByID, arg.PlaylistID, arg.ID)
	var i GetPlaylistByIDRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.CoverPath,
		&i.CoverUrl,
		&i.Labels,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SongCount,
	)
	return i, err
}

const insertAutoCreatedPlaylist = `-- name: InsertAutoCreatedPlaylist :execlastid
INSERT INTO playlists (type, name, description, cover_path, cover_url, labels)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAutoCreatedPlaylistParams struct {
	Type        string
	Name        string
	Description string
	CoverPath   string
	CoverUrl    string
	Labels      string
}

func (q *Queries) InsertAutoCreatedPlaylist(ctx context.Context, arg InsertAutoCreatedPlaylistParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAutoCreatedPlaylist,
		arg.Type,
		arg.Name,
		arg.Description,
		arg.CoverPath,
		arg.CoverUrl,
		arg.Labels,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listAllPlaylistNames = `-- name: ListAllPlaylistNames :many
SELECT name FROM playlists
`

func (q *Queries) ListAllPlaylistNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllPlaylistNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchPlaylist = `-- name: TouchPlaylist :execrows
UPDATE playlists SET updated_at = ? WHERE id = ?
`

type TouchPlaylistParams struct {
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) TouchPlaylist(ctx context.Context, arg TouchPlaylistParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchPlaylist, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePlaylist = `-- name: UpdatePlaylist :execrows
UPDATE playlists SET
    name = ?, description = ?, cover_path = ?, cover_url = ?, labels = ?, updated_at = ?
WHERE id = ?
`

type UpdatePlaylistParams struct {
	Name        string
	Description string
	CoverPath   string
	CoverUrl    string
	Labels      string
	UpdatedAt   time.Time
	ID          int64
}

func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePlaylist,
		arg.Name,
		arg.Description,
		arg.CoverPath,
		arg.CoverUrl,
		arg.Labels,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePlaylistPosition = `-- name: UpdatePlaylistPosition :execrows
UPDATE playlists SET position = ? WHERE id = ?
`

type UpdatePlaylistPositionParams struct {
	Position int64
	ID       int64
}

func (q *Queries) UpdatePlaylistPosition(ctx context.Context, arg UpdatePlaylistPositionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePlaylistPosition, arg.Position, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
