// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: songs.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const clearAllCachePaths = `-- name: ClearAllCachePaths :exec
UPDATE songs SET cache_path = '', updated_at = CURRENT_TIMESTAMP WHERE cache_path != ''
`

func (q *Queries) ClearAllCachePaths(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearAllCachePaths)
	return err
}

const clearAllFingerprints = `-- name: ClearAllFingerprints :exec
UPDATE songs SET fingerprint = '', fingerprint_duration = 0 WHERE type = 'local' AND fingerprint != ''
`

func (q *Queries) ClearAllFingerprints(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearAllFingerprints)
	return err
}

const clearCachePath = `-- name: ClearCachePath :exec
UPDATE songs SET cache_path = '', updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) ClearCachePath(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearCachePath, id)
	return err
}

const countLocalFingerprints = `-- name: CountLocalFingerprints :one
SELECT
    COUNT(*) AS total,
    CAST(COALESCE(SUM(CASE WHEN fingerprint != '' THEN 1 ELSE 0 END), 0) AS INTEGER) AS computed
FROM songs WHERE type = 'local'
`

type CountLocalFingerprintsRow struct {
	Total    int64
	Computed int64
}

func (q *Queries) CountLocalFingerprints(ctx context.Context) (CountLocalFingerprintsRow, error) {
	row := q.db.QueryRowContext(ctx, countLocalFingerprints)
	var i CountLocalFingerprintsRow
	err := row.Scan(&i.Total, &i.Computed)
	return i, err
}

const countPlaylistsByCoverPath = `-- name: CountPlaylistsByCoverPath :one
SELECT COUNT(*) FROM playlists WHERE cover_path = ?
`

func (q *Queries) CountPlaylistsByCoverPath(ctx context.Context, coverPath string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlaylistsByCoverPath, coverPath)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlaylistsContainingSong = `-- name: CountPlaylistsContainingSong :one
SELECT COUNT(*) FROM playlist_songs WHERE song_id = ?
`

func (q *Queries) CountPlaylistsContainingSong(ctx context.Context, songID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlaylistsContainingSong, songID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSongsByCoverPath = `-- name: CountSongsByCoverPath :one
SELECT COUNT(*) FROM songs WHERE cover_path = ?
`

func (q *Queries) CountSongsByCoverPath(ctx context.Context, coverPath string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSongsByCoverPath, coverPath)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSong = `-- name: CreateSong :execlastid
INSERT INTO songs (
    type, title, artist, album, duration, file_path, url,
    cover_path, cover_url, lyric, lyric_source, lyric_remote_url,
    file_size, format, bit_rate, sample_rate, is_live,
    plugin_entry_path, source_data, dedup_key,
    year, genre, language, style,
    fingerprint, fingerprint_duration,
    isrc, track,
    cue_source_path, cue_track_index, cue_audio_path,
    file_modified_at, is_video,
    cue_start_seconds, cue_end_seconds
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSongParams struct {
	Type                string
	Title               string
	Artist              string
	Album               string
	Duration            float64
	FilePath            string
	Url                 string
	CoverPath           string
	CoverUrl            string
	Lyric               string
	LyricSource         string
	LyricRemoteUrl      string
	FileSize            int64
	Format              string
	BitRate             int64
	SampleRate          int64
	IsLive              int64
	PluginEntryPath     string
	SourceData          string
	DedupKey            string
	Year                int64
	Genre               string
	Language            string
	Style               string
	Fingerprint         string
	FingerprintDuration float64
	Isrc                string
	Track               string
	CueSourcePath       string
	CueTrackIndex       int64
	CueAudioPath        string
	FileModifiedAt      sql.NullTime
	IsVideo             int64
	CueStartSeconds     float64
	CueEndSeconds       float64
}

func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createSong,
		arg.Type,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.Duration,
		arg.FilePath,
		arg.Url,
		arg.CoverPath,
		arg.CoverUrl,
		arg.Lyric,
		arg.LyricSource,
		arg.LyricRemoteUrl,
		arg.FileSize,
		arg.Format,
		arg.BitRate,
		arg.SampleRate,
		arg.IsLive,
		arg.PluginEntryPath,
		arg.SourceData,
		arg.DedupKey,
		arg.Year,
		arg.Genre,
		arg.Language,
		arg.Style,
		arg.Fingerprint,
		arg.FingerprintDuration,
		arg.Isrc,
		arg.Track,
		arg.CueSourcePath,
		arg.CueTrackIndex,
		arg.CueAudioPath,
		arg.FileModifiedAt,
		arg.IsVideo,
		arg.CueStartSeconds,
		arg.CueEndSeconds,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteByCueSource = `-- name: DeleteByCueSource :execrows
DELETE FROM songs WHERE cue_source_path = ?
`

func (q *Queries) DeleteByCueSource(ctx context.Context, cueSourcePath string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteByCueSource, cueSourcePath)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSong = `-- name: DeleteSong :execrows
DELETE FROM songs WHERE id = ?
`

func (q *Queries) DeleteSong(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSong, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findSongByDedupKey = `-- name: FindSongByDedupKey :one
SELECT id FROM songs WHERE plugin_entry_path = ? AND dedup_key = ?
`

type FindSongByDedupKeyParams struct {
	PluginEntryPath string
	DedupKey        string
}

func (q *Queries) FindSongByDedupKey(ctx context.Context, arg FindSongByDedupKeyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, findSongByDedupKey, arg.PluginEntryPath, arg.DedupKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSongByID = `-- name: GetSongByID :one
SELECT id, type, title, artist, album, duration, file_path, url,
    cover_path, cover_url, lyric, lyric_source, file_size,
    format, bit_rate, sample_rate, is_live,
    plugin_entry_path, source_data, dedup_key,
    added_at, updated_at, lyric_remote_url,
    year, genre,
    fingerprint, fingerprint_duration,
    isrc, cache_path,
    cue_source_path, cue_track_index, cue_audio_path,
    file_modified_at, track, language, style, is_video,
    cue_start_seconds, cue_end_seconds
FROM songs WHERE id = ?
`

func (q *Queries) GetSongByID(ctx context.Context, id int64) (Song, error) {
	row := q.db.QueryRowContext(ctx, getSongByID, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.Duration,
		&i.FilePath,
		&i.Url,
		&i.CoverPath,
		&i.CoverUrl,
		&i.Lyric,
		&i.LyricSource,
		&i.FileSize,
		&i.Format,
		&i.BitRate,
		&i.SampleRate,
		&i.IsLive,
		&i.PluginEntryPath,
		&i.SourceData,
		&i.DedupKey,
		&i.AddedAt,
		&i.UpdatedAt,
		&i.LyricRemoteUrl,
		&i.Year,
		&i.Genre,
		&i.Fingerprint,
		&i.FingerprintDuration,
		&i.Isrc,
		&i.CachePath,
		&i.CueSourcePath,
		&i.CueTrackIndex,
		&i.CueAudioPath,
		&i.FileModifiedAt,
		&i.Track,
		&i.Language,
		&i.Style,
		&i.IsVideo,
		&i.CueStartSeconds,
		&i.CueEndSeconds,
	)
	return i, err
}

const getSongTimestamps = `-- name: GetSongTimestamps :one
SELECT added_at, updated_at FROM songs WHERE id = ?
`

type GetSongTimestampsRow struct {
	AddedAt   time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetSongTimestamps(ctx context.Context, id int64) (GetSongTimestampsRow, error) {
	row := q.db.QueryRowContext(ctx, getSongTimestamps, id)
	var i GetSongTimestampsRow
	err := row.Scan(&i.AddedAt, &i.UpdatedAt)
	return i, err
}

const listCueAudioPaths = `-- name: ListCueAudioPaths :many
SELECT DISTINCT cue_audio_path
FROM songs WHERE cue_source_path = ? AND cue_audio_path != ''
`

func (q *Queries) ListCueAudioPaths(ctx context.Context, cueSourcePath string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCueAudioPaths, cueSourcePath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var cue_audio_path string
		if err := rows.Scan(&cue_audio_path); err != nil {
			return nil, err
		}
		items = append(items, cue_audio_path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCueSources = `-- name: ListCueSources :many
SELECT DISTINCT cue_source_path
FROM songs WHERE cue_source_path != ''
`

func (q *Queries) ListCueSources(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCueSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var cue_source_path string
		if err := rows.Scan(&cue_source_path); err != nil {
			return nil, err
		}
		items = append(items, cue_source_path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuplicateFingerprints = `-- name: ListDuplicateFingerprints :many
SELECT fingerprint, COUNT(*) AS cnt
FROM songs
WHERE fingerprint != '' AND type = 'local'
GROUP BY fingerprint
HAVING COUNT(*) > 1
`

type ListDuplicateFingerprintsRow struct {
	Fingerprint string
	Cnt         int64
}

func (q *Queries) ListDuplicateFingerprints(ctx context.Context) ([]ListDuplicateFingerprintsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDuplicateFingerprints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDuplicateFingerprintsRow{}
	for rows.Next() {
		var i ListDuplicateFingerprintsRow
		if err := rows.Scan(&i.Fingerprint, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalSongPaths = `-- name: ListLocalSongPaths :many
SELECT id, file_path, duration, cue_source_path FROM songs WHERE type = 'local'
`

type ListLocalSongPathsRow struct {
	ID            int64
	FilePath      string
	Duration      float64
	CueSourcePath string
}

func (q *Queries) ListLocalSongPaths(ctx context.Context) ([]ListLocalSongPathsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLocalSongPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLocalSongPathsRow{}
	for rows.Next() {
		var i ListLocalSongPathsRow
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.Duration,
			&i.CueSourcePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalWithoutFingerprint = `-- name: ListLocalWithoutFingerprint :many
SELECT id, file_path FROM songs WHERE type = 'local' AND fingerprint = ''
`

type ListLocalWithoutFingerprintRow struct {
	ID       int64
	FilePath string
}

func (q *Queries) ListLocalWithoutFingerprint(ctx context.Context) ([]ListLocalWithoutFingerprintRow, error) {
	rows, err := q.db.QueryContext(ctx, listLocalWithoutFingerprint)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLocalWithoutFingerprintRow{}
	for rows.Next() {
		var i ListLocalWithoutFingerprintRow
		if err := rows.Scan(&i.ID, &i.FilePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongsByFingerprint = `-- name: ListSongsByFingerprint :many
SELECT id, type, title, artist, album, duration, file_path,
    format, bit_rate, sample_rate, file_size, fingerprint_duration,
    cover_path, cover_url, added_at
FROM songs
WHERE fingerprint = ?
`

type ListSongsByFingerprintRow struct {
	ID                  int64
	Type                string
	Title               string
	Artist              string
	Album               string
	Duration            float64
	FilePath            string
	Format              string
	BitRate             int64
	SampleRate          int64
	FileSize            int64
	FingerprintDuration float64
	CoverPath           string
	CoverUrl            string
	AddedAt             time.Time
}

func (q *Queries) ListSongsByFingerprint(ctx context.Context, fingerprint string) ([]ListSongsByFingerprintRow, error) {
	rows, err := q.db.QueryContext(ctx, listSongsByFingerprint, fingerprint)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSongsByFingerprintRow{}
	for rows.Next() {
		var i ListSongsByFingerprintRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Duration,
			&i.FilePath,
			&i.Format,
			&i.BitRate,
			&i.SampleRate,
			&i.FileSize,
			&i.FingerprintDuration,
			&i.CoverPath,
			&i.CoverUrl,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongsNeedingMetadata = `-- name: ListSongsNeedingMetadata :many
SELECT id, plugin_entry_path, source_data, url,
    title, artist, album, duration,
    bit_rate, sample_rate, format, cover_path, cover_url
FROM songs
WHERE type = 'remote' AND (
    duration = 0 OR duration IS NULL
    OR bit_rate = 0 OR sample_rate = 0 OR format = ''
)
`

type ListSongsNeedingMetadataRow struct {
	ID              int64
	PluginEntryPath string
	SourceData      string
	Url             string
	Title           string
	Artist          string
	Album           string
	Duration        float64
	BitRate         int64
	SampleRate      int64
	Format          string
	CoverPath       string
	CoverUrl        string
}

func (q *Queries) ListSongsNeedingMetadata(ctx context.Context) ([]ListSongsNeedingMetadataRow, error) {
	rows, err := q.db.QueryContext(ctx, listSongsNeedingMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSongsNeedingMetadataRow{}
	for rows.Next() {
		var i ListSongsNeedingMetadataRow
		if err := rows.Scan(
			&i.ID,
			&i.PluginEntryPath,
			&i.SourceData,
			&i.Url,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Duration,
			&i.BitRate,
			&i.SampleRate,
			&i.Format,
			&i.CoverPath,
			&i.CoverUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongsWithCache = `-- name: ListSongsWithCache :many
SELECT id, type, title, artist, album, duration, file_path, url,
    cover_path, cover_url, lyric, lyric_source, file_size,
    format, bit_rate, sample_rate, is_live,
    plugin_entry_path, source_data, dedup_key,
    added_at, updated_at, lyric_remote_url,
    year, genre,
    fingerprint, fingerprint_duration,
    isrc, cache_path,
    cue_source_path, cue_track_index, cue_audio_path,
    file_modified_at, track, language, style, is_video,
    cue_start_seconds, cue_end_seconds
FROM songs WHERE cache_path != ''
`

func (q *Queries) ListSongsWithCache(ctx context.Context) ([]Song, error) {
	rows, err := q.db.QueryContext(ctx, listSongsWithCache)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Song{}
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Duration,
			&i.FilePath,
			&i.Url,
			&i.CoverPath,
			&i.CoverUrl,
			&i.Lyric,
			&i.LyricSource,
			&i.FileSize,
			&i.Format,
			&i.BitRate,
			&i.SampleRate,
			&i.IsLive,
			&i.PluginEntryPath,
			&i.SourceData,
			&i.DedupKey,
			&i.AddedAt,
			&i.UpdatedAt,
			&i.LyricRemoteUrl,
			&i.Year,
			&i.Genre,
			&i.Fingerprint,
			&i.FingerprintDuration,
			&i.Isrc,
			&i.CachePath,
			&i.CueSourcePath,
			&i.CueTrackIndex,
			&i.CueAudioPath,
			&i.FileModifiedAt,
			&i.Track,
			&i.Language,
			&i.Style,
			&i.IsVideo,
			&i.CueStartSeconds,
			&i.CueEndSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCachePath = `-- name: UpdateCachePath :exec
UPDATE songs SET cache_path = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateCachePathParams struct {
	CachePath string
	ID        int64
}

func (q *Queries) UpdateCachePath(ctx context.Context, arg UpdateCachePathParams) error {
	_, err := q.db.ExecContext(ctx, updateCachePath, arg.CachePath, arg.ID)
	return err
}

const updateRemoteSongMutable = `-- name: UpdateRemoteSongMutable :exec
UPDATE songs SET
    title = ?,
    artist = ?,
    album = ?,
    cover_url = ?,
    source_data = ?,
    duration = CASE WHEN ? > 0 THEN ? ELSE duration END,
    lyric = CASE WHEN ? != '' THEN ? ELSE lyric END,
    lyric_source = CASE WHEN ? != '' THEN ? ELSE lyric_source END,
    lyric_remote_url = CASE WHEN ? != '' THEN ? ELSE lyric_remote_url END,
    year = CASE WHEN ? > 0 THEN ? ELSE year END,
    genre = CASE WHEN ? != '' THEN ? ELSE genre END
WHERE id = ?
`

type UpdateRemoteSongMutableParams struct {
	Title          string
	Artist         string
	Album          string
	CoverUrl       string
	SourceData     string
	Column6        interface{}
	Duration       float64
	Column8        interface{}
	Lyric          string
	Column10       interface{}
	LyricSource    string
	Column12       interface{}
	LyricRemoteUrl string
	Column14       interface{}
	Year           int64
	Column16       interface{}
	Genre          string
	ID             int64
}

func (q *Queries) UpdateRemoteSongMutable(ctx context.Context, arg UpdateRemoteSongMutableParams) error {
	_, err := q.db.ExecContext(ctx, updateRemoteSongMutable,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.CoverUrl,
		arg.SourceData,
		arg.Column6,
		arg.Duration,
		arg.Column8,
		arg.Lyric,
		arg.Column10,
		arg.LyricSource,
		arg.Column12,
		arg.LyricRemoteUrl,
		arg.Column14,
		arg.Year,
		arg.Column16,
		arg.Genre,
		arg.ID,
	)
	return err
}

const updateSong = `-- name: UpdateSong :execrows
UPDATE songs SET
    type = ?, title = ?, artist = ?, album = ?, duration = ?,
    file_path = ?, url = ?, cover_path = ?, cover_url = ?,
    lyric = ?, lyric_source = ?, lyric_remote_url = ?,
    file_size = ?, format = ?, bit_rate = ?, sample_rate = ?, is_live = ?,
    plugin_entry_path = ?, source_data = ?, dedup_key = ?,
    year = ?, genre = ?, language = ?, style = ?,
    fingerprint = ?, fingerprint_duration = ?,
    isrc = ?, track = ?,
    cue_source_path = ?, cue_track_index = ?, cue_audio_path = ?,
    file_modified_at = ?, is_video = ?,
    cue_start_seconds = ?, cue_end_seconds = ?
WHERE id = ?
`

type UpdateSongParams struct {
	Type                string
	Title               string
	Artist              string
	Album               string
	Duration            float64
	FilePath            string
	Url                 string
	CoverPath           string
	CoverUrl            string
	Lyric               string
	LyricSource         string
	LyricRemoteUrl      string
	FileSize            int64
	Format              string
	BitRate             int64
	SampleRate          int64
	IsLive              int64
	PluginEntryPath     string
	SourceData          string
	DedupKey            string
	Year                int64
	Genre               string
	Language            string
	Style               string
	Fingerprint         string
	FingerprintDuration float64
	Isrc                string
	Track               string
	CueSourcePath       string
	CueTrackIndex       int64
	CueAudioPath        string
	FileModifiedAt      sql.NullTime
	IsVideo             int64
	CueStartSeconds     float64
	CueEndSeconds       float64
	ID                  int64
}

func (q *Queries) UpdateSong(ctx context.Context, arg UpdateSongParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSong,
		arg.Type,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.Duration,
		arg.FilePath,
		arg.Url,
		arg.CoverPath,
		arg.CoverUrl,
		arg.Lyric,
		arg.LyricSource,
		arg.LyricRemoteUrl,
		arg.FileSize,
		arg.Format,
		arg.BitRate,
		arg.SampleRate,
		arg.IsLive,
		arg.PluginEntryPath,
		arg.SourceData,
		arg.DedupKey,
		arg.Year,
		arg.Genre,
		arg.Language,
		arg.Style,
		arg.Fingerprint,
		arg.FingerprintDuration,
		arg.Isrc,
		arg.Track,
		arg.CueSourcePath,
		arg.CueTrackIndex,
		arg.CueAudioPath,
		arg.FileModifiedAt,
		arg.IsVideo,
		arg.CueStartSeconds,
		arg.CueEndSeconds,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSongDuration = `-- name: UpdateSongDuration :exec
UPDATE songs SET duration = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND (duration = 0 OR duration IS NULL)
`

type UpdateSongDurationParams struct {
	Duration float64
	ID       int64
}

func (q *Queries) UpdateSongDuration(ctx context.Context, arg UpdateSongDurationParams) error {
	_, err := q.db.ExecContext(ctx, updateSongDuration, arg.Duration, arg.ID)
	return err
}

const updateSongFingerprint = `-- name: UpdateSongFingerprint :exec
UPDATE songs SET fingerprint = ?, fingerprint_duration = ? WHERE id = ?
`

type UpdateSongFingerprintParams struct {
	Fingerprint         string
	FingerprintDuration float64
	ID                  int64
}

func (q *Queries) UpdateSongFingerprint(ctx context.Context, arg UpdateSongFingerprintParams) error {
	_, err := q.db.ExecContext(ctx, updateSongFingerprint, arg.Fingerprint, arg.FingerprintDuration, arg.ID)
	return err
}

const updateSongLyrics = `-- name: UpdateSongLyrics :execrows
UPDATE songs SET lyric = ?, lyric_source = ?, lyric_remote_url = ? WHERE id = ?
`

type UpdateSongLyricsParams struct {
	Lyric          string
	LyricSource    string
	LyricRemoteUrl string
	ID             int64
}

func (q *Queries) UpdateSongLyrics(ctx context.Context, arg UpdateSongLyricsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSongLyrics,
		arg.Lyric,
		arg.LyricSource,
		arg.LyricRemoteUrl,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSongMetadata = `-- name: UpdateSongMetadata :exec
UPDATE songs SET
    duration    = CASE WHEN duration = 0    AND ? > 0   THEN ? ELSE duration END,
    bit_rate    = CASE WHEN bit_rate = 0    AND ? > 0   THEN ? ELSE bit_rate END,
    sample_rate = CASE WHEN sample_rate = 0 AND ? > 0   THEN ? ELSE sample_rate END,
    format      = CASE WHEN format = ''     AND ? != '' THEN ? ELSE format END,
    title       = CASE WHEN title = ''      AND ? != '' THEN ? ELSE title END,
    artist      = CASE WHEN artist = ''     AND ? != '' THEN ? ELSE artist END,
    album       = CASE WHEN album = ''      AND ? != '' THEN ? ELSE album END,
    cover_path  = CASE WHEN cover_path = '' AND ? != '' THEN ? ELSE cover_path END,
    updated_at  = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateSongMetadataParams struct {
	Column1    interface{}
	Duration   float64
	Column3    interface{}
	BitRate    int64
	Column5    interface{}
	SampleRate int64
	Column7    interface{}
	Format     string
	Column9    interface{}
	Title      string
	Column11   interface{}
	Artist     string
	Column13   interface{}
	Album      string
	Column15   interface{}
	CoverPath  string
	ID         int64
}

func (q *Queries) UpdateSongMetadata(ctx context.Context, arg UpdateSongMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateSongMetadata,
		arg.Column1,
		arg.Duration,
		arg.Column3,
		arg.BitRate,
		arg.Column5,
		arg.SampleRate,
		arg.Column7,
		arg.Format,
		arg.Column9,
		arg.Title,
		arg.Column11,
		arg.Artist,
		arg.Column13,
		arg.Album,
		arg.Column15,
		arg.CoverPath,
		arg.ID,
	)
	return err
}

const updateSongSource = `-- name: UpdateSongSource :exec
UPDATE songs SET plugin_entry_path = ?, source_data = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateSongSourceParams struct {
	PluginEntryPath string
	SourceData      string
	ID              int64
}

func (q *Queries) UpdateSongSource(ctx context.Context, arg UpdateSongSourceParams) error {
	_, err := q.db.ExecContext(ctx, updateSongSource, arg.PluginEntryPath, arg.SourceData, arg.ID)
	return err
}

const updateSongTagFields = `-- name: UpdateSongTagFields :exec
UPDATE songs SET
    title  = CASE WHEN ? != '' THEN ? ELSE title END,
    artist = CASE WHEN ? != '' THEN ? ELSE artist END,
    album  = CASE WHEN ? != '' THEN ? ELSE album END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateSongTagFieldsParams struct {
	Column1 interface{}
	Title   string
	Column3 interface{}
	Artist  string
	Column5 interface{}
	Album   string
	ID      int64
}

func (q *Queries) UpdateSongTagFields(ctx context.Context, arg UpdateSongTagFieldsParams) error {
	_, err := q.db.ExecContext(ctx, updateSongTagFields,
		arg.Column1,
		arg.Title,
		arg.Column3,
		arg.Artist,
		arg.Column5,
		arg.Album,
		arg.ID,
	)
	return err
}
