// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: songs.sql

package sqlc

import (
	"context"
	"time"
)

const countPlaylistsByCoverPath = `-- name: CountPlaylistsByCoverPath :one
SELECT COUNT(*) FROM playlists WHERE cover_path = ?
`

func (q *Queries) CountPlaylistsByCoverPath(ctx context.Context, coverPath string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlaylistsByCoverPath, coverPath)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlaylistsContainingSong = `-- name: CountPlaylistsContainingSong :one
SELECT COUNT(*) FROM playlist_songs WHERE song_id = ?
`

func (q *Queries) CountPlaylistsContainingSong(ctx context.Context, songID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlaylistsContainingSong, songID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSongsByCoverPath = `-- name: CountSongsByCoverPath :one
SELECT COUNT(*) FROM songs WHERE cover_path = ?
`

func (q *Queries) CountSongsByCoverPath(ctx context.Context, coverPath string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSongsByCoverPath, coverPath)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSong = `-- name: CreateSong :execlastid
INSERT INTO songs (
    type, title, artist, album, duration, file_path, url,
    cover_path, cover_url, lyric, lyric_source, lyric_remote_url,
    file_size, format, bit_rate, sample_rate, is_live,
    plugin_entry_path, source_data, dedup_key
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSongParams struct {
	Type            string
	Title           string
	Artist          string
	Album           string
	Duration        float64
	FilePath        string
	Url             string
	CoverPath       string
	CoverUrl        string
	Lyric           string
	LyricSource     string
	LyricRemoteUrl  string
	FileSize        int64
	Format          string
	BitRate         int64
	SampleRate      int64
	IsLive          int64
	PluginEntryPath string
	SourceData      string
	DedupKey        string
}

func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createSong,
		arg.Type,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.Duration,
		arg.FilePath,
		arg.Url,
		arg.CoverPath,
		arg.CoverUrl,
		arg.Lyric,
		arg.LyricSource,
		arg.LyricRemoteUrl,
		arg.FileSize,
		arg.Format,
		arg.BitRate,
		arg.SampleRate,
		arg.IsLive,
		arg.PluginEntryPath,
		arg.SourceData,
		arg.DedupKey,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteSong = `-- name: DeleteSong :execrows
DELETE FROM songs WHERE id = ?
`

func (q *Queries) DeleteSong(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSong, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findSongByDedupKey = `-- name: FindSongByDedupKey :one
SELECT id FROM songs WHERE plugin_entry_path = ? AND dedup_key = ?
`

type FindSongByDedupKeyParams struct {
	PluginEntryPath string
	DedupKey        string
}

func (q *Queries) FindSongByDedupKey(ctx context.Context, arg FindSongByDedupKeyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, findSongByDedupKey, arg.PluginEntryPath, arg.DedupKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSongByID = `-- name: GetSongByID :one
SELECT id, type, title, artist, album, duration, file_path, url,
    cover_path, cover_url, lyric, lyric_source, file_size,
    format, bit_rate, sample_rate, is_live,
    plugin_entry_path, source_data, dedup_key,
    added_at, updated_at, lyric_remote_url
FROM songs WHERE id = ?
`

func (q *Queries) GetSongByID(ctx context.Context, id int64) (Song, error) {
	row := q.db.QueryRowContext(ctx, getSongByID, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.Duration,
		&i.FilePath,
		&i.Url,
		&i.CoverPath,
		&i.CoverUrl,
		&i.Lyric,
		&i.LyricSource,
		&i.FileSize,
		&i.Format,
		&i.BitRate,
		&i.SampleRate,
		&i.IsLive,
		&i.PluginEntryPath,
		&i.SourceData,
		&i.DedupKey,
		&i.AddedAt,
		&i.UpdatedAt,
		&i.LyricRemoteUrl,
	)
	return i, err
}

const getSongTimestamps = `-- name: GetSongTimestamps :one
SELECT added_at, updated_at FROM songs WHERE id = ?
`

type GetSongTimestampsRow struct {
	AddedAt   time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetSongTimestamps(ctx context.Context, id int64) (GetSongTimestampsRow, error) {
	row := q.db.QueryRowContext(ctx, getSongTimestamps, id)
	var i GetSongTimestampsRow
	err := row.Scan(&i.AddedAt, &i.UpdatedAt)
	return i, err
}

const listLocalSongPaths = `-- name: ListLocalSongPaths :many
SELECT id, file_path FROM songs WHERE type = 'local'
`

type ListLocalSongPathsRow struct {
	ID       int64
	FilePath string
}

func (q *Queries) ListLocalSongPaths(ctx context.Context) ([]ListLocalSongPathsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLocalSongPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLocalSongPathsRow{}
	for rows.Next() {
		var i ListLocalSongPathsRow
		if err := rows.Scan(&i.ID, &i.FilePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRemoteSongMutable = `-- name: UpdateRemoteSongMutable :exec
UPDATE songs SET
    title = ?,
    artist = ?,
    album = ?,
    cover_url = ?,
    source_data = ?,
    duration = CASE WHEN ? > 0 THEN ? ELSE duration END,
    lyric = CASE WHEN ? != '' THEN ? ELSE lyric END,
    lyric_source = CASE WHEN ? != '' THEN ? ELSE lyric_source END,
    lyric_remote_url = CASE WHEN ? != '' THEN ? ELSE lyric_remote_url END
WHERE id = ?
`

type UpdateRemoteSongMutableParams struct {
	Title          string
	Artist         string
	Album          string
	CoverUrl       string
	SourceData     string
	Column6        interface{}
	Duration       float64
	Column8        interface{}
	Lyric          string
	Column10       interface{}
	LyricSource    string
	Column12       interface{}
	LyricRemoteUrl string
	ID             int64
}

func (q *Queries) UpdateRemoteSongMutable(ctx context.Context, arg UpdateRemoteSongMutableParams) error {
	_, err := q.db.ExecContext(ctx, updateRemoteSongMutable,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.CoverUrl,
		arg.SourceData,
		arg.Column6,
		arg.Duration,
		arg.Column8,
		arg.Lyric,
		arg.Column10,
		arg.LyricSource,
		arg.Column12,
		arg.LyricRemoteUrl,
		arg.ID,
	)
	return err
}

const updateSong = `-- name: UpdateSong :execrows
UPDATE songs SET
    type = ?, title = ?, artist = ?, album = ?, duration = ?,
    file_path = ?, url = ?, cover_path = ?, cover_url = ?,
    lyric = ?, lyric_source = ?, lyric_remote_url = ?,
    file_size = ?, format = ?, bit_rate = ?, sample_rate = ?, is_live = ?,
    plugin_entry_path = ?, source_data = ?, dedup_key = ?
WHERE id = ?
`

type UpdateSongParams struct {
	Type            string
	Title           string
	Artist          string
	Album           string
	Duration        float64
	FilePath        string
	Url             string
	CoverPath       string
	CoverUrl        string
	Lyric           string
	LyricSource     string
	LyricRemoteUrl  string
	FileSize        int64
	Format          string
	BitRate         int64
	SampleRate      int64
	IsLive          int64
	PluginEntryPath string
	SourceData      string
	DedupKey        string
	ID              int64
}

func (q *Queries) UpdateSong(ctx context.Context, arg UpdateSongParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSong,
		arg.Type,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.Duration,
		arg.FilePath,
		arg.Url,
		arg.CoverPath,
		arg.CoverUrl,
		arg.Lyric,
		arg.LyricSource,
		arg.LyricRemoteUrl,
		arg.FileSize,
		arg.Format,
		arg.BitRate,
		arg.SampleRate,
		arg.IsLive,
		arg.PluginEntryPath,
		arg.SourceData,
		arg.DedupKey,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSongDuration = `-- name: UpdateSongDuration :exec
UPDATE songs SET duration = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND (duration = 0 OR duration IS NULL)
`

type UpdateSongDurationParams struct {
	Duration float64
	ID       int64
}

func (q *Queries) UpdateSongDuration(ctx context.Context, arg UpdateSongDurationParams) error {
	_, err := q.db.ExecContext(ctx, updateSongDuration, arg.Duration, arg.ID)
	return err
}

const updateSongLyrics = `-- name: UpdateSongLyrics :execrows
UPDATE songs SET lyric = ?, lyric_source = ?, lyric_remote_url = ? WHERE id = ?
`

type UpdateSongLyricsParams struct {
	Lyric          string
	LyricSource    string
	LyricRemoteUrl string
	ID             int64
}

func (q *Queries) UpdateSongLyrics(ctx context.Context, arg UpdateSongLyricsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSongLyrics,
		arg.Lyric,
		arg.LyricSource,
		arg.LyricRemoteUrl,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSongSource = `-- name: UpdateSongSource :exec
UPDATE songs SET plugin_entry_path = ?, source_data = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateSongSourceParams struct {
	PluginEntryPath string
	SourceData      string
	ID              int64
}

func (q *Queries) UpdateSongSource(ctx context.Context, arg UpdateSongSourceParams) error {
	_, err := q.db.ExecContext(ctx, updateSongSource, arg.PluginEntryPath, arg.SourceData, arg.ID)
	return err
}
