// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const cleanExpiredTokens = `-- name: CleanExpiredTokens :execrows
DELETE FROM auth_tokens WHERE expires_at < ?
`

func (q *Queries) CleanExpiredTokens(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, cleanExpiredTokens, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createToken = `-- name: CreateToken :execlastid
INSERT INTO auth_tokens (
    token_id, token_type, client_info, expires_at, revoked_at,
    revoked_by, created_at, revoked_reason
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTokenParams struct {
	TokenID       string
	TokenType     string
	ClientInfo    string
	ExpiresAt     time.Time
	RevokedAt     sql.NullTime
	RevokedBy     string
	CreatedAt     time.Time
	RevokedReason string
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createToken,
		arg.TokenID,
		arg.TokenType,
		arg.ClientInfo,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.RevokedBy,
		arg.CreatedAt,
		arg.RevokedReason,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getTokenByID = `-- name: GetTokenByID :one
SELECT id, token_id, token_type, client_info, expires_at, revoked_at,
    revoked_by, created_at, revoked_reason
FROM auth_tokens WHERE token_id = ?
`

type GetTokenByIDRow struct {
	ID            int64
	TokenID       string
	TokenType     string
	ClientInfo    string
	ExpiresAt     time.Time
	RevokedAt     sql.NullTime
	RevokedBy     string
	CreatedAt     time.Time
	RevokedReason string
}

func (q *Queries) GetTokenByID(ctx context.Context, tokenID string) (GetTokenByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTokenByID, tokenID)
	var i GetTokenByIDRow
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.TokenType,
		&i.ClientInfo,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.CreatedAt,
		&i.RevokedReason,
	)
	return i, err
}

const isTokenRevoked = `-- name: IsTokenRevoked :one
SELECT EXISTS(
    SELECT 1 FROM auth_tokens
    WHERE token_id = ? AND (revoked_at IS NOT NULL OR expires_at < ?)
)
`

type IsTokenRevokedParams struct {
	TokenID   string
	ExpiresAt time.Time
}

func (q *Queries) IsTokenRevoked(ctx context.Context, arg IsTokenRevokedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isTokenRevoked, arg.TokenID, arg.ExpiresAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokeToken = `-- name: RevokeToken :execrows
UPDATE auth_tokens
SET revoked_at = ?, revoked_by = ?, revoked_reason = ?
WHERE token_id = ?
`

type RevokeTokenParams struct {
	RevokedAt     sql.NullTime
	RevokedBy     string
	RevokedReason string
	TokenID       string
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeToken,
		arg.RevokedAt,
		arg.RevokedBy,
		arg.RevokedReason,
		arg.TokenID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
